CREATE TABLE roles (
    id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    created_at DATETIME2(6) NOT NULL DEFAULT SYSDATETIME(),
    deleted BIT NOT NULL DEFAULT 0,
    deleted_at DATETIME2(6) NOT NULL DEFAULT SYSDATETIME(),
    updated_at DATETIME2(6) NOT NULL DEFAULT SYSDATETIME(),
    name VARCHAR(30) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (name)
);