spring:
  application:
    name: back

  # Data source
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=shenzhen;encrypt=false
    username: sa
    password: S3guro!Pass
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      pool-name: HikariDataSource
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true
# Server configurations
server:
  error:
    include-stacktrace: never
# JWT
api:
  security:
    secret: 96fbe8547677e92c18a10f72c4c72050ab1943c6605881c1fbf11a07ce5a4378
    # Cambiar y meter en variable de entorno
    expiration: 86400000
    refresh-token:
      expiration: 604800000
#CORS
cors:
  allowed:
    origins: http://localhost:4200