CREATE TABLE users (
    id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    created_at DATETIME2(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME2(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at DATETIME2(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BIT NOT NULL DEFAULT 0,
    email VARCHAR(50) NOT NULL UNIQUE,
    first_names VARCHAR(50) NOT NULL,
    last_names VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    token VARCHAR(255) NULL UNIQUE
);
