CREATE TABLE roles (
    id UNIQUEIDENTIFIER NOT NULL,
    created_at DATETIME2(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BIT NOT NULL DEFAULT 0,
    deleted_at DATETIME2(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME2(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(30) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (name)
);